version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "ビルド前"
  build:
    commands:
      - echo "ビルド中"
      - tar -zcvf dist.tar.gz bin dist codedeploy
  post_build:
    commands:
      - echo "ビルド後"

artifacts:
  files:
    - ./dist.tar.gz